'\" t
.\" $Id$
.TH UNIQBEG 7WN "Dec 2006" "WordNet 3.0" "WordNet\(tm"
.SH NAME
uniqbeg \- unique beginners for noun hierarchies
.SH DESCRIPTION
All of the WordNet noun synsets are organized into hierarchies, headed
by the unique beginner synset for \fBentity\fP in the file
\fBnoun.Tops\fP. 

.RS
.nf
{ entity (that which is perceived or known or inferred to have its own 
distinct existence (living or nonliving)) }

.fi
.RE
.SH NOTES
The lexicographer files are not included in the WordNet database package.
.SH FILES
.TP 20
.B noun.Tops
unique beginners for nouns
.SH SEE ALSO
.BR wndb (5WN),
.BR wninput (5WN),
.BR wnintro (7WN),
.BR wngloss (7WN).
