'\" t
.\" $Id$
.tr ~
.TH WNINTRO 1WN "Dec 2006" "WordNet 3.0" "WordNet\(tm User Commands"
.SH NAME
wnintro \- WordNet user commands
.SH SYNOPSIS
.LP
\fBwn\fP \- command line interface to WordNet database
.LP
\fBwnb\fP \- window based WordNet browser
.SH DESCRIPTION
This section of the \fIWordNet Reference Manual\fP contains manual
pages that describe commands available with the various WordNet system
packages.

The WordNet interfaces 
.BR wn (1WN)
and
.BR wnb (1WN)
allow the user to search the WordNet database and display the
information textually.  
.SH ENVIRONMENT VARIABLES (UNIX)
.TP 20
.B WNHOME
Base directory for WordNet.  Default is
\fB/usr/local/WordNet-3.0\fP.
.TP 20
.B WNSEARCHDIR
Directory in which the WordNet database has been installed.  
Default is \fBWNHOME/dict\fP.
.SH REGISTRY (WINDOWS)
.TP 20
.B HKEY_LOCAL_MACHINE\eSOFTWARE\eWordNet\e3.0\eWNHome
Base directory for WordNet.  Default is
\fBC:\eProgram~Files\eWordNet\e3.0\fP.
.SH SEE ALSO
.BR grind (1WN),
.BR wn (1WN),
.BR wnb (1WN),
.BR wnintro (3WN),
.BR wnintro (5WN),
.BR wnintro (7WN).
.LP
Fellbaum, C. (1998), ed.
\fI"WordNet: An Electronic Lexical Database"\fP.
MIT Press, Cambridge, MA.
.SH AVAILABILITY
WordNet has a World Wide Web site at
\fBhttp://wordnet.princeton.edu\fP.  From this web site
users can learn about the WordNet project, run several different
interfaces to the WordNet database, and download various WordNet
system packages and \fI"Five Papers on WordNet"\fP.
