'\" t
.\" $Id$
.tr ~
.TH WNINTRO 7WN "Dec 2006" "WordNet 3.0" "Miscellaneous WordNet\(tm Topics"
.SH NAME
wnintro \- introduction to miscellaneous WordNet information
.SH SYNOPSIS
.LP
\fBmorphy\fP \- discussion of WordNet's morphological processing
.LP
\fBuniqbeg\fP \- unique beginners for noun hierarchies
.LP
\fBwngloss\fP \- glossary of terms used in WordNet
.LP
\fBwngroups\fP \- discussion of WordNet search code to group similar senses
.LP
\fBwnlicens\fP \- text of WordNet license agreement
.LP
\fBwnpkgs\fP \- information about WordNet packages and distribution
.LP
\fBwnstats\fP \- database statistics
.SH DESCRIPTION
This section of the \fIWordNet Reference Manual\fP contains manual pages
that describe various topics related to WordNet and the semantic
concordances, and a glossary of terms.
.SH SEE ALSO
.BR wnintro (1WN),
.BR wnintro (3WN),
.BR wnintro (5WN),
.BR morphy (7WN),
.BR uniqbeg (7WN),
.BR wngroups (7WN),
.BR wnlicens (7WN),
.BR wnpkgs (7WN),
.BR wnstats (7WN),
.BR wngloss (7WN).
.LP
Fellbaum, C. (1998), ed.
\fI"WordNet: An Electronic Lexical Database"\fP.
MIT Press, Cambridge, MA.
