from typing import Any, Optional, Dict, Iterator
from ..vocab import Vocab

class MorphAnalysis:
    def __init__(
        self, vocab: Vocab, features: Optional[Dict[Any, Any]] = ...
    ) -> None: ...
    @classmethod
    def from_id(cls, vocab: Vocab, key: Any) -> MorphAnalysis: ...
    def __contains__(self, feature: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: MorphAnalysis) -> bool: ...
    def __ne__(self, other: MorphAnalysis) -> bool: ...
    def get(self, field: Any) -> Any: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[Any, Any]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
