name: universe validation

on:
  push:
    branches-ignore:
      - "spacy.io"
      - "nightly.spacy.io"
      - "v2.spacy.io"
    paths:
      - "website/meta/universe.json"
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "website/meta/universe.json"

permissions: {}

jobs:
  validate:
    name: Validate
    if: github.repository_owner == 'explosion'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

      - name: Configure Python version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: "3.7"

      - name: Validate website/meta/universe.json
        run: |
          python .github/validate_universe_json.py website/meta/universe.json
